### ISSUE TITLE
could AFL-SILK  skip deterministic stage ? Thanks.

### ISSUE THREAD

**Issue by Ricardo-609** [White-Mouse/AFL-SILK#1]

**Comment by White-Mouse** [comment]
No, In fact, the power scheduling algorithm of AFL-SILK mainly works in the deterministic stage. AFL-SLAVE (i.e. the original AFL) is in havoc stage.

**Comment by Ricardo-609** [comment]
So, the havoc stage’ power scheduling is still raw version ? Could you tell me the idea you did ?

**Comment by White-Mouse** [comment]
If only one AFL-SILK instance is started, the new power scheduling algorithm works in two mutation stages. If one AFL-SILK instance and one AFL-SLAVE instance are started,  the new power scheduling algorithm only works in deterministic stage.  AFL-SILK is part of the prototype system of my paper, in order to fit better with hybrid fuzzing.  My paper is under submission and I cannot reveal more details. Sorry.
